refugio/apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

# from apps.mascota.views import index,mascota_view, mascota_list
from . import views

app_name = 'mascota'
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('nuevo', views.mascota_view, name='mascota_crear'),
#     path('listar', views.mascota_list, name='mascota_listar'),
#     path('editar/<id_mascota>', views.mascota_edit, name='mascota_editar'),
#     path('eliminar/<id_mascota>', views.mascota_delete, name='mascota_eliminar'),
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('nuevo', login_required(views.MascotaCreate.as_view()), name='mascota_crear'),
    path('listar', login_required(views.MascotaList.as_view()), name='mascota_listar'),
    path('editar/<pk>', login_required(views.MascotaUpdate.as_view()), name='mascota_editar'),
    path('eliminar/<pk>', login_required(views.MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado', views.listadousuarios, name='listado'),
]

refugio/refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls')),
    path('adopcion/', include('apps.adopcion.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/index.html'), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

refugio/apps/mascota/models.py
from pyexpat import model
from django.db import models

from apps.adopcion.models import Persona

# Create your models here.

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=10)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

refugio/apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad aproximada',
            'fecha_rescate': 'Fecha de rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'sexo' : forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada' : forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate' : forms.TextInput(attrs={'class':'form-control'}),
            'persona' : forms.Select(attrs={'class':'form-control'}),
            'vacuna' : forms.CheckboxSelectMultiple(),
        }

refugio/apps/mascota/views.py
from dataclasses import fields
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.core import serializers
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
# from django.views import generic
# from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.
def listadousuarios(request):
    lista = serializers.serialize('json', User.objects.all(), fields=['username', 'first_name'])
    return HttpResponse(lista, content_type='application/json')

def index(request):
    return render(request, 'mascota/index.html')

def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    contexto = {'mascotas' : mascota}
    return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id = id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_listar')
    return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    ordering = ['id']
    paginate_by = 4

class MascotaCreate(SuccessMessageMixin, CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')
    success_message = 'Registro creado Satisfactoriamente.'

class MascotaUpdate(SuccessMessageMixin, UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_listar')
    success_message = 'Registro actualizado Satisfactoriamente.'


class MascotaDelete(SuccessMessageMixin, DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_listar')
    success_message = 'Registro Eliminado Satisfactoriamente.'

refugio/templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title %}App Mascota{% endblock %}

{% block header %}
<h4 class="text-center mt-5">Este es el Bloque del Header Index de la App Mascota</h4>
{% endblock %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% block content %}
<div class="container-fluid">
    <h2>Mascotas</h2>

    <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi architecto tenetur et consequuntur, non quis animi officiis, tempore cupiditate iste, sed totam iusto nostrum explicabo corrupti odio corporis nam! Consequuntur!</h5>

    <section>
        <h3>Título</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Officia nisi in cumque ipsa nam inventore praesentium nostrum consequatur. Facilis quae iste reiciendis autem dicta ullam iure praesentium ipsam necessitatibus deserunt?</p>
    </section>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Type</th>
            <th scope="col">Column heading</th>
            <th scope="col">Column heading</th>
            <th scope="col">Column heading</th>
        </tr>
        </thead>
        <tbody>
        <tr class="table-active">
            <th scope="row">Active</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr>
            <th scope="row">Default</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-primary">
            <th scope="row">Primary</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-secondary">
            <th scope="row">Secondary</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-success">
            <th scope="row">Success</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-danger">
            <th scope="row">Danger</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-warning">
            <th scope="row">Warning</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-info">
            <th scope="row">Info</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-light">
            <th scope="row">Light</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr class="table-dark">
            <th scope="row">Dark</th>
            <td>Column content</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock%}

refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4>Eliminar registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
        <button type="submit" class="btn btn-outline-primary">Aceptar</button>
        <a class="btn btn-outline-danger" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block title %}Registro de Mascotas{% endblock %}

{% block header %}
<div class="container-fluid">
    <h4>Crear nuevos registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-primary">Guardar</button>
    </form>
</div>
{% endblock %}

refugio/templates/mascota/mascota_list copy.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4 class="text-center">Listado de Registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <td>#</td>
                <td>Nombre</td>
                <td>Sexo</td>
                <td>Edad</td>
                <td>Fecha de Rescate</td>
                <td>Adoptante</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if mascotas %}
            {% for mascota in mascotas %}
                <tr class="table-active">
                    <th scope="row">{{ mascota.id }}</th>
                    <td>{{ mascota.nombre }}</td>
                    <td>{{ mascota.sexo }}</td>
                    <td>{{ mascota.edad_aproximada }}</td>
                    <td>{{ mascota.fecha_rescate }}</td>
                    <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellido }}</td>
                    <td>
                        <a class="btn btn-outline-success" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-outline-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
            {% else %}
                <h1>No Existen Registros de Mascotas</h1>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4 class="text-center">Listado de Registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <td>#</td>
                <td>Nombre</td>
                <td>Sexo</td>
                <td>Edad</td>
                <td>Fecha de Rescate</td>
                <td>Adoptante</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for mascota in object_list %}
                <tr class="table-active">
                    <th scope="row">{{ mascota.id }}</th>
                    <td>{{ mascota.nombre }}</td>
                    <td>{{ mascota.sexo }}</td>
                    <td>{{ mascota.edad_aproximada }}</td>
                    <td>{{ mascota.fecha_rescate }}</td>
                    <td>{{ mascota.persona.nombre }} {{ mascota.persona.apellido }}</td>
                    <td>
                        <a class="btn btn-outline-success" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-outline-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
            {% else %}
                <h1>No Existen Registros de Mascotas</h1>
            {% endif %}
        </tbody>
    </table>
    <!-- DJANGO PAGINATION -->
    <!-- <ul class="text-center">
        <li>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
        </li>
        <li>
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            {% endif %}
        </li>
    </ul> -->
    <!-- BOOTSTRAP PAGINATION -->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-disabled="True">Previous</a>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" aria-disabled="True">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}