refugio/apps/adopcion/urls.py
from django.urls import path

# from apps.adopcion.views import index
from . import views

app_name = 'adopcion'
urlpatterns = [
    path('', views.index, name='index'),
    path('solicitud/listar',views.SolicitudList.as_view(), name='solicitud_listar'),
    path('solicitud/nueva',views.SolicitudCreate.as_view(), name='solicitud_crear'),
    path('solicitud/editar/<pk>',views.SolicitudUpdate.as_view(), name='solicitud_editar'),
    path('solicitud/eliminar/<pk>',views.SolicitudDelete.as_view(), name='solicitud_eliminar'),
]

refugio/refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls')),
    path('adopcion/', include('apps.adopcion.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/index.html'), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

refugio/apps/adopcion/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    edad = models.IntegerField()
    telefono = models.CharField(max_length=12)
    email = models.EmailField()
    direccion = models.TextField()

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()

refugio/apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = [
            'nombre',
            'apellido',
            'edad',
            'telefono',
            'email',
            'direccion',
        ]
        labels = {
            'nombre': 'Nombre',
            'apellido': 'Apellido',
            'edad': 'Edad',
            'telefono': 'Teléfono',
            'email': 'Correo Electrónico',
            'direccion': 'Dirección',
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido' : forms.TextInput(attrs={'class':'form-control'}),
            'edad' : forms.TextInput(attrs={'class':'form-control'}),
            'telefono' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.TextInput(attrs={'class':'form-control'}),
            'direccion' : forms.Textarea(attrs={'class':'form-control'}),
        }

class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = [
            'numero_mascotas',
            'razones',
        ]
        labels = {
            'numero_mascotas': 'Número de mascotas',
            'razones': 'Razones para adoptar',
        }
        widgets = {
            'numero_mascotas' : forms.TextInput(attrs={'class':'form-control'}),
            'razones' : forms.Textarea(attrs={'class':'form-control'}),
        }

refugio/apps/adopcion/views.py
from multiprocessing import context
from re import template
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm

# Create your views here.
def index(request):
    return HttpResponse('Inicio Pagina Adopción')

class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'
    ordering = ['id']

class SolicitudCreate(SuccessMessageMixin, CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    success_message = 'Registro creado Satisfactoriamente.'

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class SolicitudUpdate(SuccessMessageMixin, UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    success_message = 'Registro actualizado Satisfactoriamente.'

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id= id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST, instance=solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(SuccessMessageMixin, DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')
    success_message = 'Registro eliminado Satisfactoriamente.'

refugio/templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4>Eliminar registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro de {{ object.persona.nombre }} {{ object.persona.apellido }}?</h3>
        <button type="submit" class="btn btn-outline-primary">Aceptar</button>
        <a class="btn btn-outline-danger" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
    </form>
</div>
{% endblock %}

refugio/templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4 class="text-center mt-4">Crear nuevos registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
                    {{form2.nombre}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.nombre.apellido}}">{{form2.apellido.label}}</label>
                    {{form2.apellido}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
                    {{form2.edad}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
                    {{form2.telefono}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.email.name}}">{{form2.email.label}}</label>
                    {{form2.email}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form2.direccion.name}}">{{form2.direccion.label}}</label>
                    {{form2.direccion}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
                    {{form.numero_mascotas}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label for="{{form.razones.name}}">{{form.razones.label}}</label>
                    {{form.razones}}
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-primary float-right">Guardar</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

refugio/templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}


{% block header %}
<div class="container-fluid">
    <h4 class="text-center">Listado de Registros</h4>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <td>N° de Solicitud</td>
                <td>Adoptante</td>
                <td>N° de Mascota</td>
                <td>Razones</td>
                <td>Acciones</td>
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for solicitud in object_list %}
                <tr class="table-active">
                    <th scope="row">{{ solicitud.id }}</th>
                    <td>{{ solicitud.persona.nombre }} {{ solicitud.persona.apellido }}</td>
                    <td>{{ solicitud.numero_mascotas }}</td>
                    <td>{{ solicitud.razones }}</td>
                    <td>
                        <a class="btn btn-outline-success" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
                        <a class="btn btn-outline-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
            {% else %}
                <h1>No Existen Registros de Mascotas</h1>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}