refugio/apps/adopcion/urls.py
from django.urls import path

# from apps.adopcion.views import index
from . import views

app_name = 'adopcion'
urlpatterns = [
    path('', views.index, name='index'),
    path('solicitud/listar',views.SolicitudList.as_view(), name='solicitud_listar'),
    path('solicitud/nueva',views.SolicitudCreate.as_view(), name='solicitud_crear'),
    path('solicitud/editar/<pk>',views.SolicitudUpdate.as_view(), name='solicitud_editar'),
    path('solicitud/eliminar/<pk>',views.SolicitudDelete.as_view(), name='solicitud_eliminar'),
]

refugio/apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

# from apps.mascota.views import index,mascota_view, mascota_list
from . import views

app_name = 'mascota'
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('nuevo', views.mascota_view, name='mascota_crear'),
#     path('listar', views.mascota_list, name='mascota_listar'),
#     path('editar/<id_mascota>', views.mascota_edit, name='mascota_editar'),
#     path('eliminar/<id_mascota>', views.mascota_delete, name='mascota_eliminar'),
# ]

urlpatterns = [
    path('', views.index, name='index'),
    path('nuevo', login_required(views.MascotaCreate.as_view()), name='mascota_crear'),
    path('listar', login_required(views.MascotaList.as_view()), name='mascota_listar'),
    path('editar/<pk>', login_required(views.MascotaUpdate.as_view()), name='mascota_editar'),
    path('eliminar/<pk>', login_required(views.MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado', views.listadousuarios, name='listado'),
]

refugio/refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include('apps.mascota.urls')),
    path('adopcion/', include('apps.adopcion.urls')),
    path('usuario/', include('apps.usuario.urls')),
    path('accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/index.html'), name='logout'),
    path('reset/password_reset', PasswordResetView.as_view(template_name='registration/password_reset_form.html', email_template_name='registration/password_reset_email.html'), name='password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

refugio/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block extrahead %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Document{% endblock %}</title>
</head>
<body>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Home
                    <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Features</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Mascotas</a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'mascota:mascota_crear' %}">Registrar</a>
                    <a class="dropdown-item" href="{% url 'mascota:mascota_listar' %}">Listar</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Adopciónes</a>
                    <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a>
                    <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar' %}">Listar</a>
                    <div class="dropdown-divider"></div>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Sesión</a>
                    <div class="dropdown-menu">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesión</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'login' %}">Iniciar Sesión</a>
                    {% endif %}
                    </div>
                </ul>
                <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
            </div>
        </nav>
    {% endblock %}

    {% include 'includes/messages.html' %}

    {% block header %}
    <h4>Este es el Bloque del Header Base</h4>
    {% endblock %}

    {% block content %}
    <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi architecto tenetur et consequuntur, non quis animi officiis, tempore cupiditate iste, sed totam iusto nostrum explicabo corrupti odio corporis nam! Consequuntur!</h5>
    {% endblock%}

    {% block footer %}
    <h5>Soy el Footer del Base</h5>
    {% endblock%}

    <!-- JavaScript Bundle with Popper -->
    <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block extrajs %}
    {% endblock %}
</body>
</html>